### ISSUE TITLE
Failed to open configuration file: /ccticker.cfg

### ISSUE THREAD

**Issue by scarolan** [frittna/Crypto_Coin_Ticker#3]
I feel like this is almost working.  I ran m5burner.exe according to the instructions and put the ccticker.cfg file onto the root of the SD card but it seems to be unable to read it:

```
accessing SD-Card..
SD-Card access failed !
is card inserted ?
supported: FAT&FAT32 only
successfully..
Failed to open configuration file: /ccticker.cfg
*** Memory cleared by user ***
```

Any ideas? I am wondering if my model of M5 Stack Core 2 is incompatible; I have the AWS version of this device which has a few extra features.

**Comment by scarolan** [comment]
Never mind, I got my answer, it looks like the SD card library doesn't work with the newer Core M2 AWS version

```
In file included from .pio\libdeps\m5stack-core2\SD\utility\Sd2Card.h:26:0,
                 from .pio\libdeps\m5stack-core2\SD\utility\Sd2Card.cpp:26:
.pio\libdeps\m5stack-core2\SD\utility\Sd2PinMap.h:371:2: error: #error Architecture or board not supported.
```

**Comment by frankchau93** [comment]
> 

Were you able to install it on a Core M2?

**Comment by frittna** [comment]
it's still a pending issue since i have no core2 to test myself.
