### ISSUE TITLE
API & WSS

### ISSUE THREAD

**Issue by sxti2020** [frittna/Crypto_Coin_Ticker#6]
Could you change the "api.binance.com" to "api.yshyqxx.com" and "stream.binance.com:9443" to "stream.yshyqxx.com:443"?
Because I must use VPN for access to binance.com in CHINA, the yshyqxx.com is mirror of binance.com.

**Comment by frittna** [comment]
here you have a modified version to use chinese API mirror:
`https://github.com/frittna/Crypto_Coin_Ticker/blob/master/public/M5Burner_Crypto_Coin_Ticker_chinAPI.zip`

remember: the code is **open** and i have written a **step by step instruction** for new Arduino users how to to compile with it (in Windows) when you want to modify the code for yor needs. have fun

**Comment by sxti2020** [comment]
Hi, Frittna
Thank you very very much!


frittna ***@***.***> 于2021年11月30日周二 17:13写道：

**Comment by sxti2020** [comment]
Hi,
Could you send me a modified new version to use chinese API firmware?
Thank you very much.

Best regards
1-9-2025

Xin Zhang ***@***.***> 于2021年12月9日周四 20:19写道：

**Comment by sxti2020** [comment]
Thank you very very very much!

Jerry Wang ***@***.***> 于2025年1月9日周四 20:45写道：

**Comment by frittna** [comment]
i tried it with "api.yshyqxx.com" and "stream.yshyqxx.com" and 443 like you told me years ago, this is not working, for long time. If you have working links i can try it again.

**Comment by sxti2020** [comment]
Thank you.
It did can't display ticker. I had to use the M5Burner_Crypto_Coin_Ticker
with vpn.

frittna ***@***.***> 于2025年1月10日周五 00:59写道：

**Comment by frittna** [comment]
Okay that's good to hear. But as I wrote i don't know if there is any
better address as the one from 2 years ago.
Greetings


Mit Aqua Mail Android

**Comment by sxti2020** [comment]
I found a new way to:

const char* restApiHost = "data-api.binance.vision";
 const char* wsApiHost = "testnet.binance.vision";

 const int wsApiPort = 9443;
 or
const int wsApiPort = 443;

Could you please rewrite the program and send the bin firmware for me?

Thank you so much.



frittna ***@***.***>于2025年1月13日 周一上午2:16写道：

**Comment by frittna** [comment]
Hi, i made a version for you. It seems to work with port 443 better, with 9443 there is canlde data but no price updates. It also looks like there is a slighthly different candle data format because for example i see a false spike down in "D" time frame and other things which i dont have with the regulair api/ws settings.

**Comment by sxti2020** [comment]
Thank you soooooooooooooooo much!


frittna ***@***.***> 于2025年2月9日周日 23:33写道：
