### ISSUE TITLE
Amazon M5Stack Core2  compatible?

### ISSUE THREAD

**Issue by R1zzler** [frittna/Crypto_Coin_Ticker#9]
Will your code work on a Amazon M5Stack Core2 ESP32 IoT Development Kit for AWS IoT EduKit? I'd love to try your project but I don't get any display on my Amz M5Stack. Any help would be greatly appreciated!

**Comment by Michail1** [comment]
The code doesn't work directly on the Core2.  There are several changes that would need to take place.  ie, the core2 has a touch screen for buttons while the normal unit has 3 buttons.
I too would like to see a second release which would work with the Core2.

**Comment by frittna** [comment]
i have no core2 to play with but i think it would be possible if your're good in searching the net, but not for me at the moment, and not without a core2 device. 
Maybe someone ported some other projekts to a core2 and knows exactly and can help but (maybe) the first problem could be that even a higher ESP32 board manager version for arduino causes an freeze of my code.  Its only stable in 1.0.4 Board-Manager. Further investigation would be needed or it will die with the time and the new core versions... a pity
